### ISSUE TITLE
Add explicit model for valid form and error handling

### ISSUE THREAD

**Issue by b0g3r** [piterpy-meetup/c4p2n#2]
Currently, our code transforms a big payload of Typeform webhook to small easy-to-read `dict`. But we don't have an explicit model of valid form:
https://github.com/piterpy-meetup/c4p2n/blob/6da7d525c84f3f90e3cf4e5224c068fa75585a6b/c4p2n/models.py#L94-L99

It can cause errors on this level:
https://github.com/piterpy-meetup/c4p2n/blob/6da7d525c84f3f90e3cf4e5224c068fa75585a6b/c4p2n/notion.py#L14-L25

**Comment by ave2me** [comment]
I'll take this one.
